add_executable_wrapped(cusparse cusparse.cu)
target_link_libraries(cusparse PRIVATE libcusparse)

add_executable_wrapped(cusparse_benchmark cusparse_benchmark.cu)
target_link_libraries(cusparse_benchmark PRIVATE libcusparse)
target_link_libraries(cusparse_benchmark PRIVATE benchmark::benchmark)

add_executable_wrapped(opsparse opsparse.cu)
target_link_libraries(opsparse PRIVATE libopsparse)

add_executable_wrapped(opsparse_benchmark opsparse_benchmark.cu)
target_link_libraries(opsparse_benchmark PRIVATE libopsparse)
target_link_libraries(opsparse_benchmark PRIVATE benchmark::benchmark)
